### ISSUE TITLE
Type error ArrayInformation

### ISSUE THREAD

**Issue by michiellucas** [JsonMapper/EloquentMiddleware#5]
JsonMapper\Builders\PropertyBuilder::addType(): Argument #2 ($arrayInformation) must be of type JsonMapper\ValueObjects\ArrayInformation, bool given, called in /var/www/html/vendor/json-mapper/eloquent-middleware/src/EloquentMiddleware.php on line 135

using example: https://jsonmapper.net/docs/middleware/laravel-eloquent/

**Comment by DannyvdSluijs** [comment]
I believe this repo was forgotten when  https://github.com/JsonMapper/JsonMapper/pull/137 was merged. 

Pinning JsonMapper to 2.12.0 should fix the issue for the short term as a workaround. Could you try and let me know?

**Comment by michiellucas** [comment]
Thanks, it works now !
